apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: REPLACE_WITH_ECR_REGISTRY/leave-backend:latest # CI WILL UPDATE THIS LINE
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-password
        - name: DB_NAME
          value: "leave_db"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: jwt-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
