apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  # CHANGE THESE IN PRODUCTION
  root-password: "root"
  db-user: "root"
  db-password: "root"
  jwt-secret: "super-secure-jwt-secret-key"
  db-host: "mysql"
  db-name: "leave_db"
