apiVersion: v1
kind: Namespace
metadata:
  name: leave-system
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: leave-system
type: Opaque
stringData:
  root-password: "root"
  db-user: "root"
  db-password: "root"
  db-name: "leave_db"
  db-host: "mysql.leave-system.svc.cluster.local"
  jwt-secret: "k3d-local-secret-change-in-production"
